module.exports = {
    CREATE_PRODUCT: "CREATE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    VIEW_PRODUCT: "VIEW_PRODUCT",

    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",

    VIEW_ORDERS: "VIEW_ORDERS",
    UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
    CANCEL_ORDER: "CANCEL_ORDER",

    MANAGE_USERS: "MANAGE_USERS",
    VIEW_USERS: "VIEW_USERS",

    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",

    MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",

    WRITE_REVIEW: "WRITE_REVIEW",

    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",

    CHECKOUT: "CHECKOUT",

    MANAGE_ADDRESS: "MANAGE_ADDRESS",

    VIEW_DASHBOARD: "VIEW_DASHBOARD"
};